apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: test-newk8ssa-feb11-4
  janus-idp.io/tekton: test-newk8ssa-feb11-4
  backstage.io/kubernetes-id: test-newk8ssa-feb11-4
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: test-newk8ssa-feb11-4
resources:
  - application-dev.yaml
