apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-test-newk8ssa-feb11-4-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-test-newk8ssa-feb11-4-gitops
    spec:
      serviceAccountName: test-newk8ssa-feb11-4-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=test-newk8ssa-feb11-4-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/test-newk8ssa-feb11-4-notebook -- git clone https://github.com/jdubrick-ai/test-newk8ssa-feb11-4
      restartPolicy: Never
